all:
	agda --safe matita-basics-logic.agda
	agda --safe matita-basics-relations.agda
	agda --safe matita-basics-bool.agda 
	agda --safe matita-arithmetics-nat.agda 
	agda --safe matita-arithmetics-div-and-mod.agda 
	agda --safe matita-arithmetics-exp.agda 
	agda --safe matita-arithmetics-factorial.agda 
	agda --safe matita-arithmetics-minimization.agda 
	agda --safe matita-arithmetics-primes.agda 
	agda --safe matita-arithmetics-congruence.agda 
	agda --safe matita-arithmetics-gcd.agda 
	agda --safe matita-arithmetics-chinese-reminder.agda 
	agda --safe matita-arithmetics-lstar.agda 
	agda --safe matita-arithmetics-log.agda 
	agda --safe matita-arithmetics-sqrt.agda 
	agda --safe matita-basics-types.agda 
	agda --safe matita-arithmetics-bigops.agda 
	agda --safe matita-arithmetics-sigma-pi.agda 
	agda --safe matita-arithmetics-chebyshev-chebyshev-psi.agda 
	agda --safe matita-arithmetics-binomial.agda 
	agda --safe matita-arithmetics-chebyshev-chebyshev-theta.agda 
	agda --safe matita-arithmetics-ord.agda 
	agda --safe matita-arithmetics-chebyshev-factorization.agda 
	agda --safe matita-arithmetics-chebyshev-psi-bounds.agda 
	agda --safe matita-arithmetics-chebyshev-bertrand.agda 
	agda --safe matita-basics-lists-list.agda 
	agda --safe matita-arithmetics-chebyshev-bertrand256.agda 
	agda --safe matita-arithmetics-permutation.agda 
	agda --safe matita-arithmetics-fermat-little-theorem.agda 
	agda --safe matita-arithmetics-iteration.agda 
	agda --safe matita-arithmetics-bounded-quantifiers.agda 
	agda --safe matita-arithmetics-pidgeon-hole.agda
